name: devfrff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  - beautifulsoup4
  - lxml
  - pillow
  - reportlab
  - tqdm
  - rich
  - typer
  - mypy
  - black
  - isort
  - flake8
  - gdal
  - rasterio
  - pip
  - pip:
      - img2pdf
      - rio-tiler
      - morecantile
      - mercantile
      - rio-cogeo